name: ci-bowfolios

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - name: Read Meteor release file
        id: releasefile
        uses: juliangruber/read-file-action@v1
        with:
          path: ./app/.meteor/release
      - name: Get Meteor release number
        uses: bhowell2/github-substring-action@v1
        id: releasenum
        with:
          value: ${{ steps.releasefile.outputs.content }}
          index_of_str: "METEOR@"
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: ${{steps.releasenum.outputs.substring}}
      - run: meteor npm install
      - run: meteor npm run lint
      - run: meteor npm run testcafe-ci
